spring:
  config:
    name: estadisticaCliente
  datasource:
    url: jdbc:mysql://google/estadisticaCliente?cloudSqlInstance=single-arcanum-459318-i4:southamerica-east1:client-stadistic-1&socketFactory=com.google.cloud.sql.mysql.SocketFactory
    username: root
    password: rootcontra
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

estadisticas:
  esperanzaDeVida: 76