spring:
  config:
    name: estadisticaCliente
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./data/testdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

estadisticas:
  esperanzaDeVida: 76